# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chk < Formula
  desc "Checa o status de endpoints HTTP"
  homepage "https://github.com/arthurztt/chkCLI"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.8/chk_darwin_amd64.tar.gz"
      sha256 "550c4dbfd23602de46eb2c4fbac45216803ffbc13c9099f68057e2026a926a6f"

      define_method(:install) do
        bin.install "chk
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.8/chk_darwin_arm64.tar.gz"
      sha256 "4597ee8922f1a7bceffd692c7b0dde97fae198b2505df4fae11a068c155513bf"

      define_method(:install) do
        bin.install "chk
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.8/chk_linux_amd64.tar.gz"
      sha256 "e372bacad2aebbccab8966217f5d688c5d7e8dcce2b51f107cf9486bd5ecd0a8"
      define_method(:install) do
        bin.install "chk
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.8/chk_linux_arm64.tar.gz"
      sha256 "8d6745a2e73c4c495512a4cc7a0f54e51f29858e1e530ff035bec46a390e225e"
      define_method(:install) do
        bin.install "chk
      end
    end
  end
end
