# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chk < Formula
  desc "Checa o status de endpoints HTTP"
  homepage "https://github.com/arthurztt/chkCLI"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.9/chk_darwin_amd64.tar.gz"
      sha256 "09c36d4795f6eb4dc3a264561c9d5a044d2406c90617ff27e93aa9169d4fe7cc"

      define_method(:install) do
        bin.install "chk
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.9/chk_darwin_arm64.tar.gz"
      sha256 "4a63e93655bb5298aec7452c260ea6db51251d06c5f11b7fa9053d014adbbbe9"

      define_method(:install) do
        bin.install "chk
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.9/chk_linux_amd64.tar.gz"
      sha256 "4c8006e6e51f3ce5181bf9814a202a28f88c34e8eda31a388dcdf673ba0a3662"
      define_method(:install) do
        bin.install "chk
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurztt/chkCLI/releases/download/v0.1.9/chk_linux_arm64.tar.gz"
      sha256 "de8b89d68ac03318dd6006597c9dba27d6572492a82ad2abd39e3590bbf706c8"
      define_method(:install) do
        bin.install "chk
      end
    end
  end
end
